# Theme customization.
########################################################################################################################

fields:
  app_name:
    label: App Name
    type: text
    span: left
    default: Can They Make Snow?
  app_href:
    label: App Href
    type: text
    default: "https://cantheymakesnow.com"
    span: right
